# Generated by Django 4.2.2 on 2023-10-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_rename_desc_person_desc1_rename_img_person_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc1',
            new_name='descrip1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='image',
        ),
    ]
